import type { Metadata } from "next";
import {
  Syne,
  Oxanium,
  Kanit,
  Montserrat,
  Open_Sans,
  Big_Shoulders_Display,
  Marcellus,
} from "next/font/google";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
import "./globals.scss";

const gellery = localFont({
  src: [
    {
      path: "../../public/assets/fonts/Oxanium-ExtraBold.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/Oxanium-Light.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/Oxanium-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--tp-ff-gallery",
});

const syne_heading = localFont({
  src: [
    {
      path: "../../public/assets/fonts/Azonix.otf",
      weight: "400",
      style: "normal",
    },
  ],
});
// const kanit = localFont({
//   src: [

//   ]
// })
const aladin = Kanit({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--tp-ff-aladin",
});
const syne_body = Oxanium({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--tp-ff-body",
});
// const syne_heading = Azonix({
//   // weight: ["400", "500", "600", "700", "800"],
//   weight: ["800"],
//   subsets: ["latin"],
//   variable: "--tp-ff-heading",
// });
const syne_p = Oxanium({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--tp-ff-p",
});
const syne = Oxanium({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--tp-ff-syne",
});
const big_shoulders = Open_Sans({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--tp-ff-shoulders",
});
const marcellus = Marcellus({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--tp-ff-marcellus",
});

export const metadata: Metadata = {
  title: "Liko - Creative agency & portfolio Next js Template",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/img/custom/Favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        id="body"
        suppressHydrationWarning={true}
        className={`${gellery.variable} ${aladin.variable} ${syne_body.variable} ${syne_heading.variable} ${syne_p.variable} ${syne.variable} ${big_shoulders.variable} ${marcellus.variable}`}
      >
        <ThemeProvider defaultTheme="light">{children}</ThemeProvider>
      </body>
    </html>
  );
}
